spring.application.name=diabetes-api

spring.datasource.url=jdbc:postgresql://localhost:5432/diabetes_db
spring.datasource.username=diabetes_user
spring.datasource.password=diabetes_password

spring.jpa.hibernate.ddl-auto=update
